# Generated by Django 4.2.7 on 2023-11-29 01:08

from django.db import migrations
import user_auth.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", user_auth.models.AccountManager()),
            ],
        ),
    ]
