# Generated by Django 4.2.7 on 2024-04-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'verbose_name': '출석', 'verbose_name_plural': '출석(들)'},
        ),
    ]
